// This file was autogenerated by ../bower_components/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/core/app.js', ['qu'], ['qu.model']);
goog.addDependency('../../../../src/model/constraints.js', ['qu.constraints'], ['goog.asserts']);
goog.addDependency('../../../../src/model/model.js', ['qu.model'], []);
