// This file was autogenerated by ../bower_components/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/core/app.js', ['qu'], ['qu.model', 'qu.render', 'qu.vm']);
goog.addDependency('../../../../src/model/constraints.js', ['qu.constraints'], ['goog.asserts']);
goog.addDependency('../../../../src/model/model.js', ['qu.model'], ['qu.constraints']);
goog.addDependency('../../../../src/render/render.js', ['qu.render'], ['qu.render.util']);
goog.addDependency('../../../../src/render/util.js', ['qu.render.util'], []);
goog.addDependency('../../../../src/util/util.js', ['qu.util'], []);
goog.addDependency('../../../../src/vm/viewmodel.js', ['qu.vm'], ['qu.util']);
